In [0]:
import cv2
import pafy
url = 'https://www.youtube.com/watch?v=GrvjIhG1oZc&t=1s'
video = pafy.new(url)
best=video.getbest()
best.url


30.0
720


In [0]:
cap=cv2.VideoCapture(best.url)
fps = cap.get(cv2.CAP_PROP_FPS)
print(fps)
cap.isOpened()
ret,frame=cap.read()
print(len(frame))

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
train_path="/content/drive/My Drive/task"

In [0]:
import os
import cv2
labels=os.listdir(train_path)
from google.colab.patches import cv2_imshow

In [0]:
image=cv2.imread(train_path+'/'+label+'/'+img)
print(image)

[[[ 67  57  69]
  [ 64  55  65]
  [ 68  57  65]
  ...
  [ 38  27  23]
  [ 38  27  23]
  [ 38  27  23]]

 [[ 85  72  88]
  [ 64  51  65]
  [ 55  43  55]
  ...
  [ 38  27  23]
  [ 38  27  23]
  [ 38  27  23]]

 [[133 114 139]
  [ 95  77 100]
  [ 73  56  77]
  ...
  [ 38  27  23]
  [ 38  27  23]
  [ 38  27  23]]

 ...

 [[ 34  36  37]
  [ 34  36  37]
  [ 34  36  37]
  ...
  [ 37  36  38]
  [ 37  36  38]
  [ 37  36  38]]

 [[ 34  36  37]
  [ 33  35  36]
  [ 35  34  36]
  ...
  [ 37  36  38]
  [ 37  36  38]
  [ 37  36  38]]

 [[ 34  36  37]
  [ 34  36  37]
  [ 36  35  37]
  ...
  [ 37  36  38]
  [ 37  36  38]
  [ 37  36  38]]]


In [0]:
import numpy as np
all_labels=[]
all_pictures=[]
dim=(50,50)
for label in labels:
  images=[f for f in os.listdir(train_path+'/'+label)]
  for img in images:
    pic=cv2.imread(train_path+'/'+label+'/'+img)
    pic = cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY)
    image=cv2.resize(pic,dim)
    image=image[0:10,5:15]
    all_pictures.append((np.array(image)))
    print(np.array(image))
    all_labels.append(label)











[[15 15 15 15 15 15 15 15 15 15]
 [15 15 15 15 15 15 15 15 15 15]
 [15 15 15 15 15 15 15 15 15 15]
 [15 16 15 16 15 15 15 15 15 15]
 [15 16 15 15 15 15 15 15 15 15]
 [16 16 16 16 15 15 15 15 15 15]
 [16 15 16 16 15 15 15 15 15 15]
 [16 15 16 16 15 15 15 16 15 16]
 [16 16 15 15 15 15 15 15 16 16]
 [16 15 15 15 15 16 15 15 17 16]]
[[ 11  50  68  59  16 135  86 112  57  62]
 [ 30  53  50  88  44  64  51  60  65  72]
 [ 23  77  38  74 116  69  48  68  61  58]
 [ 28  49  85  53  27  69  55  47  59  64]
 [ 40  14  97  78  54  37  38  32  55  56]
 [ 44  18  68  59  70  25  70  53  59  60]
 [ 51  29  61  93  42  58  87  82  60  59]
 [ 57  79  31  29  31  66  37  59  65  65]
 [ 84  83  49  56  24  80  37  28  68  71]
 [ 41  18  56 107  40  58  66  28  71  73]]
[[ 63  98  78  58  55  81  86  86  70  83]
 [ 81 119  48  94  63  85  90  86  93  92]
 [ 91  54  91  92 107  77  92  92  88  77]
 [ 57  39 148  25 103  57 116  98  97  89]
 [ 40  37  36  37  38  67  36  38  37  40]
 [107 108 105 105 102 1

In [0]:
np.shape(all_pictures)

(42, 10, 10)

In [0]:
x=all_pictures
y=all_labels


In [0]:
import pandas as pd
y=all_labels
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)
enc=OneHotEncoder()
y=np.reshape(y,(-1,1))
y = pd.DataFrame(enc.fit_transform(y).toarray(),index=None)
y

0    1
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   1.0  0.0
5   1.0  0.0
6   1.0  0.0
7   1.0  0.0
8   1.0  0.0
9   1.0  0.0
10  1.0  0.0
11  1.0  0.0
12  1.0  0.0
13  1.0  0.0
14  1.0  0.0
15  1.0  0.0
16  1.0  0.0
17  1.0  0.0
18  1.0  0.0
19  1.0  0.0
20  1.0  0.0
21  1.0  0.0
22  1.0  0.0
23  1.0  0.0
24  1.0  0.0
25  0.0  1.0
26  0.0  1.0
27  0.0  1.0
28  0.0  1.0
29  0.0  1.0
30  0.0  1.0
31  0.0  1.0
32  0.0  1.0
33  0.0  1.0
34  0.0  1.0
35  0.0  1.0
36  0.0  1.0
37  0.0  1.0
38  0.0  1.0
39  0.0  1.0
40  0.0  1.0
41  0.0  1.0

In [0]:
y=all_labels
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [0]:
from keras.utils import np_utils
y=np_utils.to_categorical(y, num_classes=len(labels))

In [0]:
np.shape(y)

(42, 2)

In [0]:
x=np.array(x)
x
y=np.array(y)
y
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(np.shape(x_train))
print(np.shape(x_test))

(33, 10, 10)
(9, 10, 10)


In [0]:
x_train=x_train.reshape(33,10,10,1)
x_test=x_test.reshape(9,10,10,1)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm


In [0]:
model = Sequential()

model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(10,10,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Dropout(0.5))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))


In [0]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])


In [0]:
model.fit(x_train, y_train, epochs=100, validation_data=(x_test, y_test),batch_size=32)


Train on 33 samples, validate on 9 samples
Epoch 1/100
33/33 [==============================] - 0s 706us/step - loss: 0.2489 - accuracy: 0.9091 - val_loss: 0.8688 - val_accuracy: 0.6667
Epoch 2/100
33/33 [==============================] - 0s 567us/step - loss: 0.4704 - accuracy: 0.8788 - val_loss: 0.8314 - val_accuracy: 0.6667
Epoch 3/100
33/33 [==============================] - 0s 619us/step - loss: 0.2658 - accuracy: 0.9091 - val_loss: 0.7995 - val_accuracy: 0.6667
Epoch 4/100
33/33 [==============================] - 0s 557us/step - loss: 0.2718 - accuracy: 0.8788 - val_loss: 0.7827 - val_accuracy: 0.6667
Epoch 5/100
33/33 [==============================] - 0s 551us/step - loss: 0.2508 - accuracy: 0.9091 - val_loss: 0.7870 - val_accuracy: 0.6667
Epoch 6/100
33/33 [==============================] - 0s 541us/step - loss: 0.2195 - accuracy: 0.9091 - val_loss: 0.8076 - val_accuracy: 0.6667
Epoch 7/100
33/33 [==============================] - 0s 567us/step - loss: 0.2303 - accuracy: 0.909

In [0]:

prediction = model.predict_classes(x_test)
print(prediction)
y_test

[1 0 1 0 0 0]


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [0]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3)


NameError: ignored

In [0]:
model.predict(x_test)

array([[1.0000000e+00, 3.3610876e-16],
       [1.0000000e+00, 5.6974930e-08],
       [1.0000000e+00, 1.9736567e-11],
       [1.0000000e+00, 2.7482162e-15],
       [1.0000000e+00, 7.1345486e-18],
       [1.0000000e+00, 7.4767547e-15]], dtype=float32)

In [0]:
for img in images:
    image=cv2.imread(img,cv2.IMREAD_GRAYSCALE)
    image=cv2.resize(image,dim)
    allpictures.append(np.array(img))
    alllabels.append(label)


In [0]:
images

['frame315720.jpg',
 'frame312480.jpg',
 'frame310320.jpg',
 'frame308880.jpg',
 'frame306720.jpg',
 'frame303840.jpg',
 'frame362880.jpg',
 'frame335160.jpg',
 'frame302760.jpg',
 'frame297720.jpg',
 'frame297360.jpg',
 'frame297000.jpg']